### ISSUE TITLE
deploy to windows

### ISSUE THREAD

**Issue by fmgdias** [steelmesh/steelmesh#15]
check this https://github.com/fmgdias/steelmesh/commit/ae4273c6474a3d6aa9a4bbab0c5c264d89d711f6

**Comment by DamonOehlman** [comment]
Merged in changes, but attempted to rework the current regular expression to deal with the windows path separator as well at the linux separator.

Haven't been able to test on windows as yet, but we are running up a windows test machine today.  Hopefully it works...

**Comment by fmgdias** [comment]
i think this not work in linux...in linux the separator of dir and file "\tmp\xxx"...only in windows is "C:/temp/"...
i guess path.basename(p, [ext]) is the solution...
some like this:
packageName = path.basename(packageFile);
packageName = packageName.substring(0,packageName.indexOf("."));
i need test this....

**Comment by DamonOehlman** [comment]
I did notice a problem with this during some testing today, I'll look at updating the test project tomorrow and ensure that you can at least deploy an app...

**Comment by fmgdias** [comment]
I could test the app ... I can send you an email with my version of test ...
worked well ...
